## Linear Algebra Task

1. Matrix Operation

Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]
a. A+B
b. AB
c. 3A−2B

In [9]:
import numpy as np

A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

print("a.")
print(A + B )
print("b.") 
print(np.dot(A,B))
print("c.")
print(3*A-2*B)

a.
[[ 3  1]
 [-3  7]]
b.
[[ 5  0]
 [-9 12]]
c.
[[ 4 -7]
 [ 6  1]]


2. Determinants and Inverses  

  -Find the determinant of A.
  
  -Determine whether A is invertible. If yes, calculate A−1.

In [10]:
import numpy.linalg as LA
det=LA.det(A)
print("Determinant of A =", det)
if det != 0:
    print("A is invertible")
    print("Inverse of A =\n", LA.inv(A))
else:
    print("A is not invertible")

Determinant of A = 6.0
A is invertible
Inverse of A =
 [[0.5        0.16666667]
 [0.         0.33333333]]


3. Eigenvalues and Eigenvectors  

Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]

In [11]:
C = np.array([[4, 1],[-2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:")
print(C)

print("\nEigenvalues of C:")
print(eigenvalues)

print("\nEigenvectors of C:")
print(eigenvectors)

Matrix C:
[[ 4  1]
 [-2  1]]

Eigenvalues of C:
[3. 2.]

Eigenvectors of C:
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


4. You are given a dataset of cars with the following features:Number of cylinders (x1​), Engine size in liters (x2​),  Horsepower (x3)

car 1:

x1: 4

x2:  1.5

x3: 100

and price: 20

car 2:

x1: 6

x2:  2.0

x3: 150

and price: 30

Then, find the price of a car 3 with features

x1: 8

x2:  3.0


x3: 200

price:?

In [12]:
X = np.array([[4, 1.5, 100],[6, 2, 150]])

y = np.array([20, 30])

car3 = np.array([8, 3, 200])

Xt_dot_X = np.dot(X.T, X)
Xt_dot_y = np.dot(X.T, y)
beta = np.dot(np.linalg.pinv(Xt_dot_X), (Xt_dot_y))

price_car3 = np.dot(car3, beta)
print("Predicted price for car 3:", price_car3)

Predicted price for car 3: 40.000000000002544
